### ISSUE TITLE
Setup Swiftlint on Travis.ci

### ISSUE THREAD

**Issue by lfarah** [goktugyil/EZSwiftExtensions#156]
[Tutorial here](https://alexplescan.com/posts/2016/03/03/setting-up-swiftlint-on-travis-ci/)

**Comment by inket** [comment]
No need to follow any tutorial to use swiftlint on Travis; just put `brew install swiftlint` in `install` and `swiftlint` in `script`. (5 seconds instead of the 23+ the tutorial mentions)

Besides that, maybe it's time to remove `swiftlint` completely. Even the most basic rules are ignored right now, so there's not benefit. (oh, and it kinda causes the carthage build to fail if you have a newer version of `swiftlint` installed)

**Comment by lfarah** [comment]
@inket I fixed every single issue for ```Swiftlint``` on ```EZSwiftExtensions``` at #127  and It is sooo useful! I know people at big companies that use **Swiftlint + Travis** integration.
