### ISSUE TITLE
README Cleanup

### ISSUE THREAD

**Issue by lfarah** [goktugyil/EZSwiftExtensions#268]
I think it's time for us to rewrite our `README.md`, because it is too big and confusing.

I think this is a big thing and it's open for discussion.

My idea:
- Do a **simple** README like [this one](https://github.com/lfarah/awesome-iOS-contributions/blob/master/README.md), with the most common extensions (like Dictionary, array and String)
- For more documentation, ask the user to [Go to our CocoaDocs](http://cocoadocs.org/docsets/EZSwiftExtensions/1.7/)

What do you guys think?
# Examples
- Sending feedback email by getting device information
- Having a countdown timer with `Timer.runThisEvery()`

**Comment by goktugyil** [comment]
That simple is too simple 😁  but I like the idea in general. This might be one of the longest readmes in a popular repo. 

I think to show a user how this can be valuable, we can put the extensions that solve the most common, most annoying problems in swift. 

Then if they are interested they can read the full version from a link. 

I also think that providing real life examples, instead of the classic: (writing the function name, input, output and text) is very valauble. People can learn how to solve problems they didn't think they had.

**Comment by lfarah** [comment]
Totally agree with @goktugyil. Let's come with common examples we use on our day-by-day coding

**Comment by goktugyil** [comment]
Heres my list:

toInt

array.get array.containsType, array.random, array.indexes, array.containsarray, 
blockbutton(xywh action) { }
double.tostring double.toint
cgrect(xywh)
bool.toggle
uiview(xywh)
ez.topMostVC
string.length, string.capitalizefirst, string.trim, string.isemail, string.toint
uicolor(rgb)
ez.runThisEvery
ez.runThisAfterDelay
ez.runThisInBackground
ez.runThisEvery
ez.appBuild
ez.appVersionAndBuild
ez.detectScreenShot

**Comment by Khalian** [comment]
Would this imply a github website that keeps the other changes?

**Comment by lfarah** [comment]
@Khalian http://cocoadocs.org/docsets/EZSwiftExtensions/1.7/
