### ISSUE TITLE
Array removeAll() is conflicting with Swift implementation

### ISSUE THREAD

**Issue by icefall** [goktugyil/EZSwiftExtensions#434]
When I call removeAll() of an array I get "Ambiguous use of 'removeAll' because it has implementation on the Swift.Array and EZSwiftExtensions.Array<Element>.

Example code is attached to the issue.
[RemoveAllTest.zip](https://github.com/goktugyil/EZSwiftExtensions/files/1109581/RemoveAllTest.zip)

**Comment by Khalian** [comment]
So this happens because removeAll in the EZSwift land takes variadic parameters. This causes conflict in the special case in which the num args = 0.

I added the condition that at least one arg needs to be passed to removeAll and test cases for the same. https://github.com/goktugyil/EZSwiftExtensions/pull/436

**Comment by Khalian** [comment]
@lfarah @goktugyil Can you guys look at this, this is a bug so its high priority.

**Comment by Khalian** [comment]
Merged the change. Resolving now.

**Comment by goktugyil** [comment]
A quick fix I did was do:
 
`array = []`
